version: '3'
services:
  mongodb:
    container_name: mongodb
    image: mongodb/mongodb-community-server:6.0.4-ubi8
    ports:
      - 27017:27017
    volumes:
      - mongodb_data:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=password
    networks:
      - backend
  qdrant:
    container_name: qdrant
    image: qdrant/qdrant
    ports:
      - 6333:6333
    volumes:
      - qdrant_data:/qdrant/storage:z
    networks:
      - backend

networks:
  backend: 
    name: chatbot-network

volumes:
  mongodb_data:
  qdrant_data:

