name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4.1.1

    - name: Set up Python
      uses: actions/setup-python@v5.0.0
      with:
        python-version: 3.11.6

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Build Docker image
      run: docker build -t chatbot:latest 
  test:
    runs-on: ubuntu-latest

    needs: build

    steps:
    - name: Run unit tests
      run: python -m unittest discover tests/unit -p "*test.py"

    - name: Run integration tests
      run: python -m unittest discover tests/integration -p "*test.py"
      
  security:
    runs-on: ubuntu-latest
    needs: test
      - name: Secret Detection
      uses: actions/scan@latest
      with:
        type: secret

    - name: Container Scanning
      uses: aquasecurity/trivy-action@v0.14.0
      with:
        image-ref: chatbot:latest  # Change this to your actual image reference
        vuln-type: os,library
  
